name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Ou "master" se esse for o nome da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci  # Usa 'ci' para um build mais confiável

      - name: Build do projeto
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist  # O Vite gera o build na pasta 'dist'
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
